language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: redis-cli ping

env:
  global:
  - DATABASE_URI='postgres://postgres:@localhost:5432/test'
  
script:
  - nosetests

#after_success:
#  - codecov

services:
  - redis-server
